export const enum HsrStat {
  HP = 'hp',
  ATK = 'atk',
  DEF = 'def',
  HP_PERCENT = 'hp%',
  ATK_PERCENT = 'atk%',
  DEF_PERCENT = 'def%',
  SPD = 'spd',
  CRIT_RATE = 'crit_rate%',
  CRIT_DMG = 'crit_dmg%',
  EFFECT_HIT_RATE = 'effect_hit_rate%',
  EFFECT_RES = 'effect_res%',
  BREAK_EFFECT = 'break_effect%',
  OUTGOING_HEALING = 'outgoing_healing_boost%',
  ENERGY_REGEN_RATE = 'energy_regeneration_rate%',
  PHYSICAL_DMG = 'physical_dmg_boost',
  FIRE_DMG = 'fire_dmg_boost',
  ICE_DMG = 'ice_dmg_boost',
  LIGHTNING_DMG = 'lightning_dmg_boost',
  WIND_DMG = 'wind_dmg_boost',
  QUANTUM_DMG = 'quantum_dmg_boost',
  IMAGINARY_DMG = 'imaginary_dmg_boost'
};